name: 测试
on: push
# on:
#   schedule:
#     - cron: '3 * * * *'
jobs:
  go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: use node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: node ./src/index.js
        

      
      



